# Generated by Django 4.0.2 on 2022-05-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='travel_time',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='train',
            name='travel_time',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
